DROP TABLE IF EXISTS Operator CASCADE;
DROP TABLE IF EXISTS Competitor CASCADE;
DROP TABLE IF EXISTS Competition CASCADE;
DROP TABLE IF EXISTS Participant CASCADE;
DROP TABLE IF EXISTS Results CASCADE;
